manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
      url-base: https://github.com/ftc/     # <--- CHANGE REPO
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main                   # <--- CHANGE REVISION
      import: app/west.yml
  self:
    path: config